# Generated by Django 3.2.12 on 2022-04-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cuisine', models.CharField(max_length=100, verbose_name='cuisine type')),
                ('price_range_low', models.IntegerField(default=0)),
                ('price_range_high', models.IntegerField(default=1000)),
                ('open_rice_url', models.CharField(max_length=200)),
                ('lat', models.FloatField(verbose_name='latitude')),
                ('lng', models.FloatField(verbose_name='longitude')),
            ],
        ),
    ]
