# Generated by Django 3.2.12 on 2022-04-10 07:39

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='business_hours_from',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='business_hours_to',
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='open_rice_url',
            field=models.URLField(),
        ),
    ]
