# Generated by Django 3.2.12 on 2022-04-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_db', '0008_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='picture',
            field=models.ImageField(null=True, upload_to='restaurants'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
