# Generated by Django 3.2.12 on 2022-04-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='value',
            field=models.IntegerField(default=10),
        ),
    ]
