# Generated by Django 3.2.12 on 2022-04-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_db', '0003_alter_record_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20, verbose_name='ACTIVE, USED'),
        ),
    ]
