# Generated by Django 3.2.12 on 2022-04-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_db', '0004_alter_reward_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['date_time']},
        ),
        migrations.RemoveField(
            model_name='record',
            name='value',
        ),
        migrations.RemoveField(
            model_name='user',
            name='record',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rewards',
        ),
        migrations.AddField(
            model_name='record',
            name='balance_value',
            field=models.IntegerField(default=10, verbose_name='value change on balance'),
        ),
        migrations.AddField(
            model_name='record',
            name='g_cash_value',
            field=models.IntegerField(default=0, verbose_name='value change on g-cash'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
