# Generated by Django 3.2.12 on 2022-04-12 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_db', '0009_alter_record_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
    ]
