# Generated by Django 3.2.12 on 2022-04-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_db', '0012_alter_record_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[('B', 'BORROW'), ('R', 'RETURN'), ('T', 'TOP UP')], max_length=1),
        ),
    ]
