# Generated by Django 3.2.12 on 2022-04-12 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_db', '0003_auto_20220410_1857'),
        ('user_db', '0013_alter_record_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('P', 'Processing'), ('C', 'Completed')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_time',
            field=models.DateTimeField(verbose_name='Completed time'),
        ),
        migrations.AlterField(
            model_name='record',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants_db.restaurant'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[('B', 'BORROW'), ('R', 'RETURN'), ('T', 'TOP UP')], max_length=1, null=True),
        ),
    ]
