# Generated by Django 3.2.12 on 2022-04-13 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reward_db', '0002_coupon_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('reward_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reward_db.reward')),
            ],
            bases=('reward_db.reward',),
        ),
    ]
